name: goldenimage Workflow
on:
  workflow_call:
    inputs:
      APP:
        required: true
        type: string
      WEBHOOK_URL:
        required: true
        type: string
      REGION:
        required: true
        type: string

jobs:
  Golden-Image:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Debug Inputs
        run: |
          echo "APP: ${{ inputs.APP }}"
          echo "WEBHOOK_URL: ${{ inputs.WEBHOOK_URL }}"
          echo "REGION: ${{ inputs.REGION }}"

      - name: Notify Discord for success
        uses: sarisia/actions-status-discord@v1.15.0
        if: success() && contains(fromJSON('["${{ vars.WEBHOOK_URL }}"]'), 'http')
        with:
          nodetail: true
          webhook: ${{ vars.WEBHOOK_URL }}
          avatar_url: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
          username: ${{ inputs.APP }}
          content: Success goldenimage workflow
          description: Workflow finished successfuly
          title: New AMI was created on ${{ inputs.REGION }}
          color: 5763719