name: goldenimage Workflow
on:
  workflow_call:
      APP:
        required: true
        type: string
      PROJECT:
        required: true
        type: string

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  Golden-Image:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Notify Discord for success
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: "https://discord.com/api/webhooks/1241737791730225163/Mb1z13aBZ8cvhbZEO9meBxVIAEn1ClzVgruJ9vVqGh6E6umlZ81gpim_s_7f1nRPdaiE"
          nodetail: true
          title: "New AMI was created on ${{ inputs.PROJECT }}-${{ inputs.APP }}"
          description: "Workflow finished successfuly"
          color: 5763719
          username: GitHub
          avatar_url: "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png"