name: goldenimage Workflow
on:
  workflow_call:
    inputs:
      APP:
        required: true
        type: string
      WEBHOOK_URL:
        required: true
        type: string

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  Golden-Image:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Notify Discord for success
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: "${{ inputs.WEBHOOK_URL }}"
          nodetail: true
          title: "Workflow finished successfuly"
          description: "New AMI was created on ${{ inputs.APP }}"
          color: 5763719
          username: GitHub
          avatar_url: "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png"