name: goldenimage Workflow
on:
  workflow_call:
    inputs:
      S3_BASE_PATH:
        required: true
        type: string
      ROLE:
        required: true
        type: string
      REGION:
        required: true
        type: string
      CPU_ARCH:
        required: true
        type: string
      OS:
        required: true
        type: string
      APP:
        required: true
        type: string
      TOOLKIT_VERSION:
        required: true
        type: string

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  Golden-Image:
    runs-on: ubuntu-latest
    continue-on-error: false  
    steps:
      - name: Notify Discord for success
        if: success()
        uses: discord-actions/message@v2
        with:
          webhookUrl: https://discord.com/api/webhooks/1241737791730225163/Mb1z13aBZ8cvhbZEO9meBxVIAEn1ClzVgruJ9vVqGh6E6umlZ81gpim_s_7f1nRPdaiE
          message: "Hello, from Github"

      - name: Notify Discord for fail
        if: ${{ always() && contains(needs.*.result, 'failure') }}
        uses: discord-actions/message@v2
        with:
          webhookUrl: https://discord.com/api/webhooks/1241737791730225163/Mb1z13aBZ8cvhbZEO9meBxVIAEn1ClzVgruJ9vVqGh6E6umlZ81gpim_s_7f1nRPdaiE
          message: "Hello, from Github"