name: goldenimage Workflow
on:
  workflow_call:

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  Golden-Image:
    runs-on: ubuntu-latest
    continue-on-error: false  
    steps:
      - name: Notify Discord for success
        if: success()
        uses: discord-actions/message@v2
        with:
          webhookUrl: https://discord.com/api/webhooks/1241737791730225163/Mb1z13aBZ8cvhbZEO9meBxVIAEn1ClzVgruJ9vVqGh6E6umlZ81gpim_s_7f1nRPdaiE
          message: "Hello, thats a success" 

      - name: send message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "GitHub Bot"
          message: "A new commit has been pushed with custom color."