name: goldenimage Workflow
on:
  workflow_call:

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  Golden-Image:
    runs-on: ubuntu-latest
    continue-on-error: false  
    steps:
      
      - name: Notify Discord for success
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: "https://discord.com/api/webhooks/1241737791730225163/Mb1z13aBZ8cvhbZEO9meBxVIAEn1ClzVgruJ9vVqGh6E6umlZ81gpim_s_7f1nRPdaiE"
          nodetail: true
          title: "New version of `software` is ready!"
          description: "Build and deploy to GitHub Pages"
          color: 5763719
          username: GitHub
          avatar_url: "https://cdn-icons-png.freepik.com/256/16021/16021236.png?semt=ais_hybrid"