name: goldenimage Workflow
on:
  workflow_call:

permissions:
  id-token: write   # Required for requesting the JWT
  contents: read    # Required for actions/checkout

jobs:
  Golden-Image:
    runs-on: ubuntu-latest
    continue-on-error: false  
    steps:

      - name: send message
        uses: appleboy/discord-action@master
        with:
          webhook_id: "1241737791730225163"
          webhook_token: "Mb1z13aBZ8cvhbZEO9meBxVIAEn1ClzVgruJ9vVqGh6E6umlZ81gpim_s_7f1nRPdaiE"
          color: "#48f442"
          username: "GitHub"
          message: "workflow success."
          file: "https://cdn-icons-png.flaticon.com/512/25/25231.png"