name: goldenimage Workflow
on:
  workflow_call:
    inputs:
      APP:
        required: true
        type: string
      REGION:
        required: true
        type: string

jobs:
  Golden-Image:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Debug Inputs
        run: |
          echo "APP: ${{ inputs.APP }}"
          echo "REGION: ${{ inputs.REGION }}"
          echo "WEBHOOK_URL: ${{ vars.WEBHOOK_URL }}"

      # Check if the JSON file exists
      - name: Check for goldenimage_result.json
        id: check-file
        run: |
          if [[ -f "goldenimage_result.json" ]]; then
            echo "File goldenimage_result.json exists."
          else
            echo "File goldenimage_result.json does not exist."
            exit 1
          fi

      # Load parameters from JSON file
      - name: Load parameters from goldenimage_result.json
        id: load-parameters
        run: |
          JSON_CONTENT=$(jq '.' "goldenimage_result.json")
          echo "$JSON_CONTENT"

          TIMESTAMP=$(jq -r '.timestamp' <<< "$JSON_CONTENT")
          ALL_AMIS=$(jq '.all_amis' <<< "$JSON_CONTENT")
          APP=$(jq -r '.app' <<< "$JSON_CONTENT")
          PROFILE=$(jq -r '.profile' <<< "$JSON_CONTENT")
          REGION=$(jq -r '.region' <<< "$JSON_CONTENT")
          VERSION=$(jq -r '.version' <<< "$JSON_CONTENT")
          AMI=$(jq -r '.ami' <<< "$JSON_CONTENT")

      # Use the loaded variables
      - name: Use loaded parameters
        run: |
          echo "Using loaded variables:"
          echo "AMI: $ami"

      - name: Notify Discord for success
        uses: sarisia/actions-status-discord@v1.15.0
        if: success() && vars.WEBHOOK_URL != ''
        with:
          nodetail: true
          webhook: ${{ vars.WEBHOOK_URL }}
          avatar_url: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
          username: ${{ inputs.APP }}
          content: Success goldenimage workflow
          description: Workflow finished successfuly
          title: New AMI was created on ${{ inputs.REGION }}
          color: 5763719