name: goldenimage Workflow
on:
  workflow_call:
    inputs:
      APP:
        required: true
        type: string
      WEBHOOK_URL:
        required: true
        type: string
      REGION:
        required: true
        type: string

jobs:
  Golden-Image:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - name: Notify Discord for success
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          nodetail: true
          webhook: ${{ inputs.WEBHOOK_URL }}
          avatar_url: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
          username: ${{ inputs.APP }} goldenimage workflow
          content: Success
          description: Workflow finished successfuly
          title: New AMI was created on ${{ inputs.REGION }}
          color: 5763719